pull_request_rules:
  - name: Automatic merge when CI Passes
    conditions:
      - 'status-success=ci/circleci: test'
    actions:
      close:
        message: 'This PR has passed CI and will be closed'
      label:
        add: ['Approved for Badge']
        remove: ['Failing Tests']
  - name: Comment when CI fails
    conditions:
      - 'status-failure=ci/circleci: test'
    actions:
      comment:
        message: 'Looks like there is an error with the test files...'
      label:
        add: ['Failing Tests']
