pull_request_rules:
  - name: Automatic merge when CI Passes
    conditions:
      - 'status-success=ci/circleci: test'
    actions:
      close:
        message: 'This PR has passed CI and will be closed'
      label:
        add: ['Approved for Badge']
